export type ModeId = 'interview' | 'impromptu' | 'pitch' | 'script'

export interface Question {
  level: number
  text: string
  /** Why this question is being asked — shown under the question, helps you aim the answer. */
  probing?: string
}

export interface KnowledgeDoc {
  id: string
  name: string
  /** Extracted plain text. Truncated at import time to keep requests sane. */
  text: string
  chars: number
  addedAt: number
}

/** Locally computed, no API key needed. Always present on a take. */
export interface Metrics {
  durationSec: number
  words: number
  /** 0 when pace could not be measured — see `paceReliable`. */
  wordsPerMinute: number
  /**
   * False when the word count and the recording length clearly do not correspond —
   * a transcript that was typed or pasted rather than spoken. The coach is told pace
   * is unmeasurable rather than being handed a fabricated number to scold you for.
   */
  paceReliable: boolean
  fillerCount: number
  fillersFound: { word: string; count: number }[]
  echoedQuestion: boolean
  /** Rough Answer -> Story -> So-what structure detection. */
  openedWithAnswer: boolean
  hasConcreteExample: boolean
  endedWithPoint: boolean
  longestMonologueRun: number
  /** Script mode only: share of script key phrases that showed up in the transcript. */
  scriptCoverage?: number
  missedScriptPoints?: string[]
}

export interface Dimension {
  name: string
  score: number
  comment: string
}

/** Shape returned by /api/coach action=analyze. Mirrors ANALYSIS_SCHEMA in schemas.ts. */
export interface Analysis {
  overallScore: number
  headline: string
  dimensions: Dimension[]
  strengths: string[]
  fixes: { issue: string; quote?: string; instead: string }[]
  modelAnswer: string
  followUpQuestion: string
  /** Set by the client, not the model. */
  source: 'claude' | 'local'
  model?: string
}

export interface Take {
  id: string
  createdAt: number
  mode: ModeId
  topic: string
  question: string
  transcript: string
  metrics: Metrics
  analysis?: Analysis
  /** Object URL for the recorded blob. Lives only for the current page session. */
  mediaUrl?: string
  mediaType?: string
}

export interface Settings {
  apiKey: string
  model: string
  effort: 'low' | 'medium' | 'high' | 'xhigh' | 'max'
  targetSeconds: number
  greenZoneSeconds: number
  recognitionLang: string
  mirror: boolean
  recordVideo: boolean
}

export interface CoachRequest {
  action: 'questions' | 'analyze'
  mode: ModeId
  topic: string
  knowledge: string
  question?: string
  transcript?: string
  metrics?: Metrics
  script?: string
  level?: number
  count?: number
  targetSeconds?: number
  systemPrompt: string
  userPrompt: string
  model?: string
  effort?: Settings['effort']
}

export interface KeyStatus {
  serverKey: boolean
  model: string
}

/* ------------------------------- scenario packs ------------------------------- */

/**
 * One scored dimension of a researched rubric. This is the bridge between the prep
 * agents and the live coaching: whatever the research found the interviewer actually
 * grades on gets injected into the coaching prompt, so the score you see practising
 * is against the real rubric rather than the generic one.
 */
export interface RubricDimension {
  name: string
  weight: 'high' | 'medium' | 'low'
  /** What a strong answer on this dimension sounds like. */
  good: string
  /** The specific failure the interviewer is watching for. */
  bad: string
}

export interface Source {
  title: string
  url: string
  /** What this source actually established, so a stale link is still auditable. */
  supports: string
}

/**
 * The candidate-facing report — phase 2 of the prep pipeline. Rendered in the app's
 * Briefing tab and mirrored to `briefing.md` for reading on GitHub.
 */
export interface Briefing {
  headline: string
  /** What the round physically looks like: length, who is in the room, how it opens. */
  format: string
  whyTheyAsk: { theme: string; why: string }[]
  rubric: RubricDimension[]
  strongAnswer: string[]
  weakAnswer: string[]
  traps: { trap: string; instead: string }[]
  prepPlan: string[]
  sources: Source[]
}

/**
 * A prep pack is a saved practice setup: the mode, the topic, the grounding material,
 * the question list, and the timing. Loading one replaces those fields so you can start
 * recording without typing anything. Everything a pack sets stays editable afterwards.
 *
 * Built-in packs ship in `packs.ts`. Researched packs are generated by the agents in
 * `agents/` into `scenarios/<id>/pack.json` and carry a `briefing`.
 */
export interface PrepPack {
  id: string
  label: string
  blurb: string
  mode: ModeId
  topic: string
  targetSeconds: number
  greenZoneSeconds: number
  /** Becomes the Notes field, which feeds {{knowledge}} in every prompt. */
  notes: string
  questions: Question[]
  /** Present only on researched packs. Drives the Briefing tab and the coaching rubric. */
  briefing?: Briefing
  /** 'built-in' ships with the app; 'scenario' was generated into scenarios/. */
  origin: 'built-in' | 'scenario'
  /** ISO date the research was run, so you can tell when a pack has gone stale. */
  researchedOn?: string
}
